//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballCompetitionManagerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueSeason
    {
        public int LeagueSeasonId { get; set; }
        public int CompetitionId { get; set; }
        public bool DoubleMatches { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
}
