//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballCompetitionManagerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchId { get; set; }
        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }
        public Nullable<int> CompetitionId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public int Length { get; set; }
        public int PlayersPerTeam { get; set; }
        public Nullable<int> HomeTeamGoals { get; set; }
        public Nullable<int> AwayTeamGoals { get; set; }
        public int MatchStatusId { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual MatchStatus MatchStatus { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
